/**
 * ==========================================================================
 * DICTIONARY DICTIONARY MODULE
 * ==========================================================================
 * Stores UI content structures across local boundaries (FI and RU).
 */
const translations = {
    fi: {
        nav_services: "Palvelut",
        nav_pricing: "Hinnasto",
        nav_about: "Meistä",
        nav_contact: "Ota yhteyttä",
        
        hero_subtitle: "Nopea & Luotettava IT-Tuki",
        hero_title: "Tietokoneesi kuntoon ilman stressiä",
        hero_desc: "Ammattitaitoinen tietokonehuolto ja IT-tuki alueellasi. Korjaamme laitteet, optimoimme järjestelmät ja opastamme turvallisessa käytössä.",
        hero_cta_primary: "Tutustu palveluihin",
        hero_cta_secondary: "Varaa huolto",
        
        services_title: "Palvelumme",
        srv_diag_title: "PC-Diagnostiikka",
        srv_diag_desc: "Vianetsintä ja laitteiston kuntotarkastus. Selvitämme ongelman syyn nopeasti ennen korjaustoimenpiteitä.",
        srv_clean_title: "Pölynpoisto & Puhdistus",
        srv_clean_desc: "Laitteiston sisäinen puhdistus pölystä ja lämpötahnojen vaihto. Ehkäisee ylikuumenemista ja pidentää käyttöikää.",
        srv_virus_title: "Virustentorjunta & Haittaohjelmat",
        srv_virus_desc: "Haittaohjelmien täydellinen poisto ja tietoturvan optimointi. Varmistamme, että järjestelmäsi on täysin turvallinen.",
        srv_soft_title: "Ohjelmistot & Päivitykset",
        srv_soft_desc: "Käyttöjärjestelmien (Windows/Mac) ja tarvittavien apuohjelmien asennus, konfigurointi sekä kriittiset päivitykset.",
        srv_build_title: "Tietokoneen kasaus osista",
        srv_build_desc: "Räätälöidyt tietokoneet pelaamiseen tai työkäyttöön. Autamme komponenttien valinnassa ja kasaamme laitteen puolestasi.",
        srv_opt_title: "Kannettavien optimointi",
        srv_opt_desc: "Hitaan kannettavan tietokoneen nopeutus, turhien taustaprosessien poisto ja tallennustilan optimointi suorituskyvyn parantamiseksi.",
        srv_backup_title: "Varmuuskopiointi",
        srv_backup_desc: "Tärkeiden valokuvien, tiedostojen ja dokumenttien turvallinen varmuuskopiointi pilvipalveluun tai ulkoiselle levylle.",
        srv_tutor_title: "Tietokoneen käytön opastus",
        srv_tutor_desc: "Henkilökohtainen ja selkeä opastus laitteen sekä digitaalisten palveluiden turvalliseen käyttöön ilman vaikeita teknisiä termejä.",
        
        pricing_title: "Hinnasto",
        price_popular: "Suosituin",
        price_p1_title: "Perushuolto",
        price_p2_title: "Tehohuolto & Turva",
        price_p3_title: "Räätälöity tuki",
        price_feat_diag: "PC-Diagnostiikka",
        price_feat_clean: "Pölynpoisto sisätiloista",
        price_feat_opt: "Järjestelmän optimointi",
        price_feat_all_basic: "Kaikki Perushuollon palvelut",
        price_feat_virus: "Virustentorjunta & puhdistus",
        price_feat_update: "Ohjelmistopäivitykset",
        price_feat_backup: "Varmuuskopioinnin määritys",
        price_feat_custom_build: "Tietokoneen kasaus osista",
        price_feat_tutor: "Henkilökohtainen opastus",
        price_feat_home: "Kotikäynnit ja asennukset",
        price_btn: "Valitse palvelu",
        
        about_subtitle: "Fixitium Tarina",
        about_title: "Luotettavaa IT-apua vuosien kokemuksella",
        about_p1: "Fixitium syntyi halusta tarjota selkeää, rehellistä ja helposti lähestyttävää tietokonehuoltoa niin yksityisille kotitalouksille kuin pienyrityksille. Emme puhu vaikeaa nörttikieltä, vaan ratkaisemme ongelmasi ymmärrettävästi.",
        about_p2: "Olipa kyseessä hidas kannettava, pelikoneen kasaus tai tietoturvahuolet, hoidamme työn tehokkaasti ja ammattitaitoisesti laatuvaatimuksista tinkimättä.",
        
        contact_title: "Ota yhteyttä",
        form_name: "Nimi",
        form_email: "Sähköposti",
        form_msg: "Viesti / Kuvaile ongelma",
        form_btn: "Lähetä viestipyyntö",
        form_success_msg: "Kiitos! Viestisi on lähetetty onnistuneesti. Otamme sinuun yhteyttä pian.",
        form_error_msg: "Hups! Jotain meni pieleen. Tarkista tiedot ja yritä uudelleen.",
        footer_rights: "Kaikki oikeudet pidätetään."
    },
    ru: {
        nav_services: "Услуги",
        nav_pricing: "Цены",
        nav_about: "О нас",
        nav_contact: "Контакты",
        
        hero_subtitle: "Быстрая и Надежная ИТ-Помощь",
        hero_title: "Ваш компьютер в надежных руках",
        hero_desc: "Профессиональный ремонт компьютеров и ИТ-поддержка рядом с вами. Исправляем неполадки, оптимизируем системы и обучаем безопасной работе.",
        hero_cta_primary: "Наши услуги",
        hero_cta_secondary: "Заказать ремонт",
        
        services_title: "Наши Услуги",
        srv_diag_title: "Диагностика ПК",
        srv_diag_desc: "Поиск неисправностей и проверка компонентов. Быстро определим точную причину поломки перед началом ремонта.",
        srv_clean_title: "Очистка от пыли",
        srv_clean_desc: "Внутренняя очистка корпуса и замена термопасты. Предотвращает перегрев и продлевает срок службы устройства.",
        srv_virus_title: "Удаление вирусов",
        srv_virus_desc: "Полная очистка системы от вирусов и вредоносных программ. Защитим ваши данные и оптимизируем безопасность.",
        srv_soft_title: "Программы и Обновления",
        srv_soft_desc: "Установка и настройка операционных систем (Windows/Mac), необходимых драйверов, утилит и критических обновлений.",
        srv_build_title: "Сборка ПК на заказ",
        srv_build_desc: "Сборка кастомных компьютеров для игр или работы. Поможем выбрать лучшие компоненты под ваш бюджет.",
        srv_opt_title: "Оптимизация ноутбуков",
        srv_opt_desc: "Ускорение работы медленных ноутбуков, отключение лишних фоновых процессов и очистка дискового пространства.",
        srv_backup_title: "Резервное копирование",
        srv_backup_desc: "Надежное сохранение важных семейных фотографий, документов и архивов в облако или на внешний жесткий диск.",
        srv_tutor_title: "Обучение компьютерной грамотности",
        srv_tutor_desc: "Понятные и простые уроки по безопасной работе на ПК и использованию цифровых сервисов без сложных терминов.",
        
        pricing_title: "Стоимость услуг",
        price_popular: "Популярно",
        price_p1_title: "Базовый сервис",
        price_p2_title: "Комплексная защита",
        price_p3_title: "Почасовая помощь",
        price_feat_diag: "Полная диагностика ПК",
        price_feat_clean: "Очистка от пыли корпуса",
        price_feat_opt: "Оптимизация системы",
        price_feat_all_basic: "Все услуги Базового сервиса",
        price_feat_virus: "Удаление вирусов и защита",
        price_feat_update: "Обновление ПО и драйверов",
        price_feat_backup: "Настройка бэкапа данных",
        price_feat_custom_build: "Сборка ПК из комплектующих",
        price_feat_tutor: "Индивидуальное обучение",
        price_feat_home: "Выезд на дом и настройка",
        price_btn: "Выбрать услугу",
        
        about_subtitle: "История Fixitium",
        about_title: "Надежная ИТ-поддержка с многолетним опытом",
        about_p1: "Проект Fixitium был создан с целью предложить понятный, честный и доступный ремонт компьютеров для частных лиц и малого бизнеса. Мы не говорим на сложном языке программистов, а решаем проблемы просто.",
        about_p2: "Будь то медленный ноутбук, сборка мощной игровой станции или проблемы с безопасностью сети — мы выполним работу эффективно и профессионально.",
        
        contact_title: "Связаться с нами",
        form_name: "Имя",
        form_email: "Электронная почта",
        form_msg: "Сообщение / Опишите проблему",
        form_btn: "Отправить запрос",
        form_success_msg: "Спасибо! Ваше сообщение успешно отправлено. Мы свяжемся с вами в ближайшее время.",
        form_error_msg: "Ой! Что-то пошло не так. Пожалуйста, проверьте данные и повторите попытку.",
        footer_rights: "Все права защищены."
    }
};
